<?php

namespace App\Actions\Customer;

use App\Exceptions\GracefulDetailedException;
use App\Helpers\TextFormatting;
use App\Models\Customer;
use App\Http\Traits\Actions\ModelActionBase;
use App\Http\Traits\Actions\ResponseMessage;
use Exception;
use Illuminate\Support\Facades\Validator;

/**
 * @method bool execute(Customer $customer, array $data = [])
 * @property Customer $actionRecord
 */
class UpdateCustomer
{
    use ModelActionBase;
    use ResponseMessage;

    /**
     * @param array $data
     */
    protected function setParameters(array $data): void
    {
        $this->data = [
            'name' => $data['name'] ?? '',
            'cnpj' => $data['cnpj'] ?? '',
        ];
    }

    /**
     * @return bool|array
     * @throws Exception
     */
    protected function main()
    {
        try {
            $this->validation();

            $this->actionRecord->name = $this->data['name'];
            $this->actionRecord->cnpj = $this->data['cnpj'];

            $this->actionRecord->save();

            return $this->responseSuccess('Cliente atualizado com sucesso');
        } catch (GracefulDetailedException $e) {
            return $this->responseFailure('inputError', $e->getMessage(), ['errors' => $e->getDetails()] ?? []);
        } catch (Exception $e) {
            return $this->responseFailure('error', $e->getMessage());
        }
    }

    /**
     * @throws Exception
     */
    private function validation()
    {
        $validator = Validator::make($this->data, [
            'name' => ['required', 'string', 'max:255'],
            'cnpj' => ['required', 'cnpj', 'unique:customers,cnpj,'.$this->actionRecord->id, 'max:18'],
        ]);

        if ($validator->fails()) {
            throw new GracefulDetailedException('Dados inv√°lidos',
                TextFormatting::getErrorsToArray($validator)
            );
        }
    }
}
